baseurl = "https://andres.reveronmolina.me"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Andrés Reverón Molina"
enableEmoji = true

[author]
  name = "Andrés Reverón Molina"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Andrés Revverón Molina"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  homeSubtitle = "Front-end Developer"
  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  subtitle = "Front-end developer"
  copyright = ""
  readOtherPosts = "Read other posts"

  [params.logo]
    logoText = "Andrés Reverón Molina"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/systemallica"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/andres-reveron"
  [[params.social]]
    name = "email"
    url  = "mailto:andres@reveronmolina.me"
  [[params.social]]
    name = "telegram"
    url  = "https://telegram.me/systemallica"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"