baseurl = "https://andres.reveronmolina.me"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Andrés Reverón Molina"
enableEmoji = true
DefaultContentLanguage = "en"

[author]
  name = "Andrés Reverón Molina"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Andrés Revverón Molina"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [languages]
    [languages.en]
      subtitle = "Front-end developer"
      homeSubtitle = "Front-end Developer"
      copyright = ""
      readOtherPosts = "Read other posts"
      keywords = ""

    [languages.en.params.logo]
      logoText = "Andrés Reverón Molina"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

    [languages.es]
      subtitle = "Desarrollador Front-end"
      homeSubtitle = "Desarrollador Front-end"
      copyright = ""
      readOtherPosts = "Lee otras publicaciones"
      keywords = ""

    [languages.es.params.logo]
      logoText = "Andrés Reverón Molina"
      logoHomeLink = "/es"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
      [[languages.es.menu.main]]
        identifier = "sobre"
        name = "Sobre mí"
        url = "/about"


  # Social icons
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/systemallica"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/andres-reveron"
  [[params.social]]
    name = "email"
    url  = "mailto:andres@reveronmolina.me"
  [[params.social]]
    name = "telegram"
    url  = "https://telegram.me/systemallica"
