# Hugo parameters
baseURL = "https://andres.reveronmolina.me/"
languageCode = "en"
title = "Andrés Reverón Molina"
theme = "coder"
canonifyurls = true

# Theme parameters
[params]
    author = "Andrés Reverón Molina"
    info = "Front-end developer"
    description = "Andrés Reverón's personal website"
    keywords = "blog,developer,personal"
    hideCredits = true
    hideCopyright = true

    # footercontent = "Enter a text here."

# Social links
[[params.social]]
    name = "GitLab"
    weight = 1
    icon = "fab fa-gitlab fa-2x"
    url = "https://gitlab.com/systemallica"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    icon = "fab fa-linkedin-in fa-2x"
    url = "https://www.linkedin.com/in/andres-reveron/"
[[params.social]]
    name = "Email"
    weight = 3
    icon = "fas fa-envelope fa-2x"
    url = "mailto:andres@reveronmolina.me"
[[params.social]]
    name = "Telegram"
    weight = 4
    icon = "fab fa-telegram-plane fa-2x"
    url = "https://telegram.me/systemallica"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"